import type { AnalysisResult } from "../rules/engine.js";
import type { Finding } from "../core/types.js";
import { ruleById } from "../rules/registry.js";
import { evidence } from "../parsers/fingerprint.js";

/**
 * `--emit-sql`: one reviewable migration file.
 *
 * DDL is deduplicated by statement text, because a dozen queries in a real slow
 * log routinely ask for the same index. Findings without DDL (pure rewrites) are
 * listed as comments instead of silently dropped.
 */
export function renderMigration(result: AnalysisResult, source: string): string {
  const withDdl = result.findings.filter((f) => f.suggestedDDL.length > 0);
  const rewrites = result.findings.filter((f) => !f.suggestedDDL.length && f.rewrite);

  const seen = new Map<string, Finding>();
  for (const finding of withDdl) {
    for (const ddl of finding.suggestedDDL) {
      const existing = seen.get(ddl);
      // Keep the most severe justification for a shared DDL.
      if (!existing || rank(finding.severity) > rank(existing.severity)) seen.set(ddl, finding);
    }
  }

  const grouped = new Map<string, Array<{ ddl: string; finding: Finding }>>();
  for (const [ddl, finding] of seen) {
    const table = finding.table ?? "(unknown)";
    const list = grouped.get(table) ?? [];
    list.push({ ddl, finding });
    grouped.set(table, list);
  }

  const out: string[] = [
    "-- Generated by sql-index-advisor (SIA) — review before running.",
    `-- Source : ${source}`,
    `-- Findings: ${result.findings.length} · DDL statements: ${seen.size} · Tables touched: ${grouped.size}`,
    "--",
    "-- 本文件只做两件事：加索引。不会 DROP、不会改数据、不会自动执行。",
    "-- 建议按表逐个执行，并在业务低峰期用 ALGORITHM=INPLACE, LOCK=NONE 验证在线 DDL 可行性。",
    "",
  ];

  for (const [table, entries] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    out.push(`-- ── ${table} ${"─".repeat(Math.max(2, 60 - table.length))}`);
    for (const { ddl, finding } of entries.sort((a, b) => a.ddl.localeCompare(b.ddl))) {
      out.push(`-- ${finding.rule} ${ruleById(finding.rule)?.title ?? ""} · ${severityNote(finding)}`);
      out.push(`--   证据: ${evidence(finding.sql, 150)}`);
      out.push(ddl);
    }
    out.push("");
  }

  if (rewrites.length > 0) {
    out.push(`-- ── 需要改写 SQL 的建议（无 DDL）${"─".repeat(24)}`);
    for (const finding of rewrites) {
      out.push(`-- ${finding.rule} · ${evidence(finding.sql, 120)}`);
      out.push(`--   ${finding.rewrite}`);
    }
    out.push("");
  }

  out.push("-- 执行后请复核未被采纳的索引：重复或极窄的索引会持续放大写入成本。");
  return `${out.join("\n")}\n`;
}

function rank(severity: Finding["severity"]): number {
  return severity === "error" ? 3 : severity === "warn" ? 2 : 1;
}

function severityNote(finding: Finding): string {
  const bits: string[] = [finding.severity];
  if (finding.occurrences && finding.occurrences > 1) bits.push(`命中 ${finding.occurrences} 次`);
  if (finding.rowsExamined !== undefined) {
    bits.push(`扫描 ${finding.rowsExamined.toLocaleString("en-US")} 行`);
  }
  return bits.join(" · ");
}
