import type { AnalysisResult } from "../rules/engine.js";
import type { Finding } from "../core/types.js";
import { ruleById } from "../rules/registry.js";
import { evidence } from "../parsers/fingerprint.js";

export interface MigrationOptions {
  lang?: "zh" | "en";
}

const TEXT = {
  zh: {
    header: "-- 本文件只做两件事：加索引。不会 DROP、不会改数据、不会自动执行。",
    hint: "-- 建议按表逐个执行，并在业务低峰期用 ALGORITHM=INPLACE, LOCK=NONE 验证在线 DDL 可行性。",
    rewrites: "-- ── 需要改写 SQL 的建议（无 DDL）",
    footer: "-- 执行后请复核未被采纳的索引：重复或极窄的索引会持续放大写入成本。",
    hits: (n: number) => `命中 ${n} 次`,
    scanned: (n: number) => `扫描 ${n.toLocaleString("en-US")} 行`,
    review: "-- Generated by sql-index-advisor (SIA)，执行前请人工评审。",
  },
  en: {
    header: "-- This file adds indexes. Nothing here drops, alters or deletes data.",
    hint: "-- Apply one table at a time, off peak, and confirm ALGORITHM=INPLACE, LOCK=NONE is accepted.",
    rewrites: "-- ── Advice that needs a SQL rewrite (no DDL)",
    footer: "-- Re-check indexes left unused afterwards: duplicates and narrow ones keep costing writes.",
    hits: (n: number) => `${n} occurrences`,
    scanned: (n: number) => `${n.toLocaleString("en-US")} rows scanned`,
    review: "-- Generated by sql-index-advisor (SIA); review before running.",
  },
} as const;

/**
 * `--emit-sql`: one reviewable migration file.
 *
 * DDL is deduplicated by statement text, because a dozen queries in a real slow
 * log routinely ask for the same index. Findings without DDL (pure rewrites) are
 * listed as comments instead of silently dropped.
 */
export function renderMigration(
  result: AnalysisResult,
  source: string,
  options: MigrationOptions = {},
): string {
  const lang = options.lang ?? "zh";
  const t = TEXT[lang];
  const withDdl = result.findings.filter((f) => f.suggestedDDL.length > 0);
  const rewrites = result.findings.filter((f) => !f.suggestedDDL.length && f.rewrite);

  const seen = new Map<string, Finding>();
  for (const finding of withDdl) {
    for (const ddl of finding.suggestedDDL) {
      const existing = seen.get(ddl);
      // Keep the most severe justification for a shared DDL.
      if (!existing || rank(finding.severity) > rank(existing.severity)) seen.set(ddl, finding);
    }
  }

  const grouped = new Map<string, Array<{ ddl: string; finding: Finding }>>();
  for (const [ddl, finding] of seen) {
    const table = finding.table ?? "(unknown)";
    const list = grouped.get(table) ?? [];
    list.push({ ddl, finding });
    grouped.set(table, list);
  }

  const out: string[] = [
    t.review,
    `-- Source : ${source}`,
    `-- Findings: ${result.findings.length} · DDL statements: ${seen.size} · Tables touched: ${grouped.size}`,
    "--",
    t.header,
    t.hint,
    /**
     * Whoever runs this file must be able to see what the file does not cover.
     * A migration generated from a directory of runtime-built predicates, or
     * without a schema, looks complete otherwise: it is a list of statements with
     * nothing saying "these other rules never got a look at your queries".
     */
    ...result.notes.map((note) => `-- ! ${lang === "en" ? note.noteEn : note.note}`),
    ...(result.skipped.length > 0
      ? [
          `-- ! ${lang === "en" ? "not evaluated" : "未参与判定"}: ${result.skipped
            .map((s) => `${s.id} (${lang === "en" ? s.reasonEn : s.reason})`)
            .join(", ")}`,
        ]
      : []),
    "",
  ];

  for (const [table, entries] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    out.push(`-- ── ${table} ${"─".repeat(Math.max(2, 60 - table.length))}`);
    for (const { ddl, finding } of entries.sort((a, b) => a.ddl.localeCompare(b.ddl))) {
      const rule = ruleById(finding.rule);
      const title = lang === "en" ? (rule?.titleEn ?? finding.rule) : (rule?.title ?? "");
      out.push(`-- ${finding.rule} ${title} · ${severityNote(finding, lang)}`);
      out.push(`--   ${lang === "en" ? "evidence" : "证据"}: ${evidence(finding.sql, 150)}`);
      out.push(ddl);
    }
    out.push("");
  }

  if (rewrites.length > 0) {
    out.push(`${t.rewrites}${"─".repeat(24)}`);
    for (const finding of rewrites) {
      out.push(`-- ${finding.rule} · ${evidence(finding.sql, 120)}`);
      out.push(`--   ${finding.rewrite}`);
    }
    out.push("");
  }

  out.push(t.footer);
  return `${out.join("\n")}\n`;
}

function rank(severity: Finding["severity"]): number {
  return severity === "error" ? 3 : severity === "warn" ? 2 : 1;
}

function severityNote(finding: Finding, lang: "zh" | "en"): string {
  const t = TEXT[lang];
  const bits: string[] = [finding.severity];
  if (finding.occurrences && finding.occurrences > 1) bits.push(t.hits(finding.occurrences));
  if (finding.rowsExamined !== undefined) bits.push(t.scanned(finding.rowsExamined));
  return bits.join(" · ");
}
